### ISSUE TITLE
Image render

### ISSUE THREAD

**Issue by Pixelcorp** [codrops/GridLayoutSlideshow#2]
Hi,
Demo2 and Demo3 no longer render images after clicking next or previous. Images render only after i resize the window. This issue seems to be only present when using Chrome.
![theme-error](https://user-images.githubusercontent.com/44774430/47999125-d59f3d80-e101-11e8-86d3-28cf55dbdde7.jpg)

**Comment by crnacura** [comment]
Hi, we've fixed this bug now, thanks for pointing out this issue!

**Comment by Pixelcorp** [comment]
Can you please let me know where the issue was and how you fixed it? I am using this theme in a modified form and would like to avoid replacing all the files.
Thank you
